# Generated by Django 5.1.4 on 2024-12-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pilot",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Male")], default="M", max_length=6
            ),
        ),
    ]
