# Generated by Django 5.1.4 on 2024-12-30 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0002_alter_pilot_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drone",
            name="drone_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drones",
                to="drones.dronecategory",
            ),
        ),
    ]
