# Generated by Django 5.1.4 on 2024-12-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0003_alter_drone_drone_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="distance_in_meters",
            field=models.IntegerField(),
        ),
    ]
