# Generated by Django 5.1.4 on 2024-12-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0004_alter_competition_distance_in_meters"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competition",
            options={"ordering": ("-distance_in_meters",)},
        ),
        migrations.AlterField(
            model_name="pilot",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Male")], default="F", max_length=6
            ),
        ),
    ]
